import type { Job, Employer } from '@/lib/types';

export const employers: Employer[] = [
  {
    id: 'innovate-inc',
    name: 'Innovate Inc.',
    logo: 'employer-logo-1',
    industry: 'Technology',
    location: 'San Francisco, CA',
    about: 'Innovate Inc. is a leading technology company specializing in AI and machine learning solutions. We are committed to pushing the boundaries of technology.',
    culture: 'We foster a collaborative and innovative environment where every team member is encouraged to grow and contribute to our mission. We offer flexible working hours and an excellent benefits package.',
    website: 'https://innovate-inc.example.com',
  },
  {
    id: 'quantum-solutions',
    name: 'Quantum Solutions',
    logo: 'employer-logo-2',
    industry: 'Software',
    location: 'New York, NY',
    about: 'Quantum Solutions provides enterprise-level software for a variety of industries. Our products are used by millions worldwide.',
    culture: 'Our culture is built on a foundation of respect, integrity, and a passion for excellence. We value our employees and provide ample opportunities for professional development.',
    website: 'https://quantum-solutions.example.com',
  },
  {
    id: 'ecovibes',
    name: 'EcoVibes',
    logo: 'employer-logo-3',
    industry: 'Sustainability',
    location: 'Austin, TX',
    about: 'EcoVibes is dedicated to creating a sustainable future through innovative green technology and environmental consulting.',
    culture: 'We are a mission-driven company with a passionate, energetic team. If you care about the planet, you\'ll feel right at home here.',
    website: 'https://ecovibes.example.com',
  },
  {
    id: 'healthwell',
    name: 'HealthWell',
    logo: 'employer-logo-4',
    industry: 'Healthcare',
    location: 'Boston, MA',
    about: 'HealthWell is a top-tier healthcare provider focused on patient-centered care and medical research.',
    culture: 'Our team is comprised of dedicated professionals who are passionate about making a difference in people\'s lives. We prioritize work-life balance and continuous learning.',
    website: 'https://healthwell.example.com',
  },
    {
    id: 'finsecure',
    name: 'FinSecure',
    logo: 'employer-logo-5',
    industry: 'Finance',
    location: 'Chicago, IL',
    about: 'FinSecure offers cutting-edge financial security services and products to individuals and businesses.',
    culture: 'We pride ourselves on our analytical rigor and commitment to client success. Our team enjoys a challenging yet rewarding work environment.',
    website: 'https://finsecure.example.com',
  },
  {
    id: 'codecrafters',
    name: 'CodeCrafters',
    logo: 'employer-logo-6',
    industry: 'Web Development',
    location: 'Remote',
    about: 'CodeCrafters is a remote-first digital agency that builds beautiful, high-performance websites and applications.',
    culture: 'As a fully distributed team, we value autonomy, communication, and a shared passion for excellent code.',
    website: 'https://codecrafters.example.com',
  },
];

export const jobs: Job[] = [
  {
    id: 'swe-innovate-1',
    title: 'Senior Software Engineer',
    companyId: 'innovate-inc',
    companyName: 'Innovate Inc.',
    companyLogo: 'employer-logo-1',
    location: 'San Francisco, CA',
    category: 'Engineering',
    type: 'Full-Time',
    salary: '$150,000 - $180,000',
    description: 'Develop and maintain our core AI platform, working with a team of talented engineers.',
    longDescription: 'As a Senior Software Engineer at Innovate Inc., you will be a key player in designing, building, and scaling our next-generation AI products. You will work on complex technical challenges and have a significant impact on our platform\'s architecture. This role requires a deep understanding of distributed systems, cloud computing, and a passion for writing clean, efficient code.',
    requirements: ['5+ years of software development experience', 'Proficiency in Python or Go', 'Experience with AWS or GCP', 'Strong problem-solving skills'],
    postedAt: '2 days ago',
  },
  {
    id: 'pm-quantum-1',
    title: 'Product Manager, Enterprise',
    companyId: 'quantum-solutions',
    companyName: 'Quantum Solutions',
    companyLogo: 'employer-logo-2',
    location: 'New York, NY',
    category: 'Product',
    type: 'Full-Time',
    salary: '$140,000 - $170,000',
    description: 'Lead the product strategy and roadmap for our flagship enterprise software.',
    longDescription: 'Quantum Solutions is seeking an experienced Product Manager to drive the vision and execution of our enterprise product suite. You will work closely with engineering, design, and marketing to define product requirements, prioritize features, and deliver solutions that meet the needs of our largest customers. The ideal candidate is a strategic thinker with a strong technical background and a proven track record of launching successful products.',
    requirements: ['4+ years of product management experience', 'Experience with B2B SaaS products', 'Excellent communication and leadership skills', 'Ability to work in a fast-paced environment'],
    postedAt: '5 days ago',
  },
  {
    id: 'ux-codecrafters-1',
    title: 'UX/UI Designer',
    companyId: 'codecrafters',
    companyName: 'CodeCrafters',
    companyLogo: 'employer-logo-6',
    location: 'Remote',
    category: 'Design',
    type: 'Contract',
    description: 'Design intuitive and beautiful user interfaces for our client projects.',
    longDescription: 'CodeCrafters is looking for a talented UX/UI Designer to create engaging and user-friendly web and mobile interfaces. You will be involved in the entire design process, from user research and wireframing to creating high-fidelity mockups and prototypes. This is a remote contract position with the potential for long-term collaboration.',
    requirements: ['3+ years of UX/UI design experience', 'Strong portfolio of web and mobile designs', 'Proficiency in Figma or Sketch', 'Excellent visual design skills'],
    postedAt: '1 week ago',
  },
    {
    id: 'da-finsecure-1',
    title: 'Data Analyst',
    companyId: 'finsecure',
    companyName: 'FinSecure',
    companyLogo: 'employer-logo-5',
    location: 'Chicago, IL',
    category: 'Data',
    type: 'Full-Time',
    salary: '$90,000 - $110,000',
    description: 'Analyze financial data to identify trends, mitigate risks, and support business decisions.',
    longDescription: 'As a Data Analyst at FinSecure, you will play a crucial role in our risk management and business intelligence efforts. You will be responsible for collecting, cleaning, and analyzing large datasets to generate actionable insights. This role requires strong analytical skills, attention to detail, and a solid understanding of financial markets.',
    requirements: ['2+ years of experience in data analysis', 'Proficiency in SQL and Python/R', 'Experience with data visualization tools like Tableau', 'Strong statistical knowledge'],
    postedAt: '3 days ago',
  },
  {
    id: 'me-ecovibes-1',
    title: 'Marketing Specialist',
    companyId: 'ecovibes',
    companyName: 'EcoVibes',
    companyLogo: 'employer-logo-3',
    location: 'Austin, TX',
    category: 'Marketing',
    type: 'Full-Time',
    description: 'Develop and execute marketing campaigns to promote our sustainability solutions.',
    longDescription: 'EcoVibes is looking for a passionate Marketing Specialist to help us grow our brand and reach a wider audience. You will be responsible for content creation, social media management, email marketing, and performance tracking. If you are a creative marketer with a passion for sustainability, we\'d love to hear from you.',
    requirements: ['3+ years of marketing experience', 'Strong writing and content creation skills', 'Experience with SEO/SEM and social media marketing', 'Passion for environmental causes'],
    postedAt: '10 days ago',
  },
  {
    id: 'rn-healthwell-1',
    title: 'Registered Nurse',
    companyId: 'healthwell',
    companyName: 'HealthWell',
    companyLogo: 'employer-logo-4',
    location: 'Boston, MA',
    category: 'Healthcare',
    type: 'Part-Time',
    description: 'Provide high-quality patient care in our state-of-the-art medical facility.',
    longDescription: 'HealthWell is hiring a part-time Registered Nurse to join our compassionate and skilled nursing team. You will be responsible for assessing patient needs, administering medications, and providing direct care and education to patients and their families. This role offers a flexible schedule and a supportive work environment.',
    requirements: ['Valid RN license', '2+ years of nursing experience', 'BLS/CPR certification', 'Excellent communication and interpersonal skills'],
    postedAt: '2 weeks ago',
  }
];

export const featuredJobs = jobs.slice(0, 3);
export const topEmployers = employers.slice(0, 4);

export const jobCategories = [...new Set(jobs.map(job => job.category))];
export const jobLocations = [...new Set(jobs.map(job => job.location))];
