import type { Job, Employer } from '@/lib/types';

export const employers: Employer[] = [
  {
    id: 'innovate-inc',
    name: 'Innovate Inc.',
    logo: 'employer-logo-1',
    industry: 'Teknologi',
    location: 'San Francisco, CA',
    about: 'Innovate Inc. adalah perusahaan teknologi terkemuka yang berspesialisasi dalam solusi AI dan machine learning. Kami berkomitmen untuk mendorong batas-batas teknologi.',
    culture: 'Kami memupuk lingkungan yang kolaboratif dan inovatif di mana setiap anggota tim didorong untuk tumbuh dan berkontribusi pada misi kami. Kami menawarkan jam kerja yang fleksibel dan paket tunjangan yang sangat baik.',
    website: 'https://innovate-inc.example.com',
  },
  {
    id: 'quantum-solutions',
    name: 'Quantum Solutions',
    logo: 'employer-logo-2',
    industry: 'Perangkat Lunak',
    location: 'New York, NY',
    about: 'Quantum Solutions menyediakan perangkat lunak tingkat perusahaan untuk berbagai industri. Produk kami digunakan oleh jutaan orang di seluruh dunia.',
    culture: 'Budaya kami dibangun di atas fondasi rasa hormat, integritas, dan semangat untuk keunggulan. Kami menghargai karyawan kami dan memberikan banyak kesempatan untuk pengembangan profesional.',
    website: 'https://quantum-solutions.example.com',
  },
  {
    id: 'ecovibes',
    name: 'EcoVibes',
    logo: 'employer-logo-3',
    industry: 'Keberlanjutan',
    location: 'Austin, TX',
    about: 'EcoVibes didedikasikan untuk menciptakan masa depan yang berkelanjutan melalui teknologi hijau inovatif dan konsultasi lingkungan.',
    culture: 'Kami adalah perusahaan yang didorong oleh misi dengan tim yang bersemangat dan energik. Jika Anda peduli dengan planet ini, Anda akan merasa betah di sini.',
    website: 'https://ecovibes.example.com',
  },
  {
    id: 'healthwell',
    name: 'HealthWell',
    logo: 'employer-logo-4',
    industry: 'Kesehatan',
    location: 'Boston, MA',
    about: 'HealthWell adalah penyedia layanan kesehatan tingkat atas yang berfokus pada perawatan yang berpusat pada pasien dan penelitian medis.',
    culture: 'Tim kami terdiri dari para profesional berdedikasi yang bersemangat membuat perbedaan dalam kehidupan orang-orang. Kami memprioritaskan keseimbangan kehidupan kerja dan pembelajaran berkelanjutan.',
    website: 'https://healthwell.example.com',
  },
    {
    id: 'finsecure',
    name: 'FinSecure',
    logo: 'employer-logo-5',
    industry: 'Keuangan',
    location: 'Chicago, IL',
    about: 'FinSecure menawarkan layanan dan produk keamanan finansial mutakhir kepada individu dan bisnis.',
    culture: 'Kami bangga dengan ketelitian analitis kami dan komitmen terhadap kesuksesan klien. Tim kami menikmati lingkungan kerja yang menantang namun memuaskan.',
    website: 'https://finsecure.example.com',
  },
  {
    id: 'codecrafters',
    name: 'CodeCrafters',
    logo: 'employer-logo-6',
    industry: 'Pengembangan Web',
    location: 'Jarak Jauh',
    about: 'CodeCrafters adalah agensi digital jarak jauh pertama yang membangun situs web dan aplikasi yang indah dan berkinerja tinggi.',
    culture: 'Sebagai tim yang sepenuhnya terdistribusi, kami menghargai otonomi, komunikasi, dan semangat bersama untuk kode yang sangat baik.',
    website: 'https://codecrafters.example.com',
  },
];

export const jobs: Job[] = [
  {
    id: 'swe-innovate-1',
    title: 'Insinyur Perangkat Lunak Senior',
    companyId: 'innovate-inc',
    companyName: 'Innovate Inc.',
    companyLogo: 'employer-logo-1',
    location: 'Jakarta',
    category: 'Rekayasa',
    type: 'Penuh Waktu',
    salary: 'Rp 25.000.000 - Rp 35.000.000',
    description: 'Mengembangkan dan memelihara platform AI inti kami, bekerja dengan tim insinyur berbakat.',
    longDescription: 'Sebagai Insinyur Perangkat Lunak Senior di Innovate Inc., Anda akan menjadi pemain kunci dalam merancang, membangun, dan menskalakan produk AI generasi berikutnya kami. Anda akan mengerjakan tantangan teknis yang kompleks dan memiliki dampak signifikan pada arsitektur platform kami. Peran ini membutuhkan pemahaman mendalam tentang sistem terdistribusi, komputasi awan, dan semangat untuk menulis kode yang bersih dan efisien.',
    requirements: ['5+ tahun pengalaman pengembangan perangkat lunak', 'Kemahiran dalam Python atau Go', 'Pengalaman dengan AWS atau GCP', 'Keterampilan pemecahan masalah yang kuat'],
    postedAt: '2 hari yang lalu',
  },
  {
    id: 'pm-quantum-1',
    title: 'Manajer Produk, Perusahaan',
    companyId: 'quantum-solutions',
    companyName: 'Quantum Solutions',
    companyLogo: 'employer-logo-2',
    location: 'Bandung',
    category: 'Produk',
    type: 'Penuh Waktu',
    salary: 'Rp 20.000.000 - Rp 30.000.000',
    description: 'Memimpin strategi produk dan peta jalan untuk perangkat lunak perusahaan andalan kami.',
    longDescription: 'Quantum Solutions mencari Manajer Produk berpengalaman untuk mendorong visi dan eksekusi rangkaian produk perusahaan kami. Anda akan bekerja sama dengan teknik, desain, dan pemasaran untuk menentukan persyaratan produk, memprioritaskan fitur, dan memberikan solusi yang memenuhi kebutuhan pelanggan terbesar kami. Kandidat ideal adalah pemikir strategis dengan latar belakang teknis yang kuat dan rekam jejak yang terbukti dalam meluncurkan produk yang sukses.',
    requirements: ['4+ tahun pengalaman manajemen produk', 'Pengalaman dengan produk B2B SaaS', 'Keterampilan komunikasi dan kepemimpinan yang sangat baik', 'Kemampuan untuk bekerja di lingkungan yang serba cepat'],
    postedAt: '5 hari yang lalu',
  },
  {
    id: 'ux-codecrafters-1',
    title: 'Desainer UX/UI',
    companyId: 'codecrafters',
    companyName: 'CodeCrafters',
    companyLogo: 'employer-logo-6',
    location: 'Jarak Jauh',
    category: 'Desain',
    type: 'Kontrak',
    description: 'Merancang antarmuka pengguna yang intuitif dan indah untuk proyek klien kami.',
    longDescription: 'CodeCrafters sedang mencari Desainer UX/UI berbakat untuk membuat antarmuka web dan seluler yang menarik dan ramah pengguna. Anda akan terlibat dalam seluruh proses desain, dari penelitian pengguna dan wireframing hingga membuat maket dan prototipe fidelitas tinggi. Ini adalah posisi kontrak jarak jauh dengan potensi kolaborasi jangka panjang.',
    requirements: ['3+ tahun pengalaman desain UX/UI', 'Portofolio desain web dan seluler yang kuat', 'Kemahiran dalam Figma atau Sketch', 'Keterampilan desain visual yang sangat baik'],
    postedAt: '1 minggu yang lalu',
  },
    {
    id: 'da-finsecure-1',
    title: 'Analis Data',
    companyId: 'finsecure',
    companyName: 'FinSecure',
    companyLogo: 'employer-logo-5',
    location: 'Surabaya',
    category: 'Data',
    type: 'Penuh Waktu',
    salary: 'Rp 15.000.000 - Rp 20.000.000',
    description: 'Menganalisis data keuangan untuk mengidentifikasi tren, memitigasi risiko, dan mendukung keputusan bisnis.',
    longDescription: 'Sebagai Analis Data di FinSecure, Anda akan memainkan peran penting dalam upaya manajemen risiko dan intelijen bisnis kami. Anda akan bertanggung jawab untuk mengumpulkan, membersihkan, dan menganalisis kumpulan data besar untuk menghasilkan wawasan yang dapat ditindaklanjuti. Peran ini membutuhkan keterampilan analitis yang kuat, perhatian terhadap detail, dan pemahaman yang kuat tentang pasar keuangan.',
    requirements: ['2+ tahun pengalaman dalam analisis data', 'Kemahiran dalam SQL dan Python/R', 'Pengalaman dengan alat visualisasi data seperti Tableau', 'Pengetahuan statistik yang kuat'],
    postedAt: '3 hari yang lalu',
  },
  {
    id: 'me-ecovibes-1',
    title: 'Spesialis Pemasaran',
    companyId: 'ecovibes',
    companyName: 'EcoVibes',
    companyLogo: 'employer-logo-3',
    location: 'Yogyakarta',
    category: 'Pemasaran',
    type: 'Penuh Waktu',
    description: 'Mengembangkan dan melaksanakan kampanye pemasaran untuk mempromosikan solusi keberlanjutan kami.',
    longDescription: 'EcoVibes mencari Spesialis Pemasaran yang bersemangat untuk membantu kami menumbuhkan merek kami dan menjangkau audiens yang lebih luas. Anda akan bertanggung jawab untuk pembuatan konten, manajemen media sosial, pemasaran email, dan pelacakan kinerja. Jika Anda adalah pemasar kreatif dengan hasrat untuk keberlanjutan, kami ingin sekali mendengar dari Anda.',
    requirements: ['3+ tahun pengalaman pemasaran', 'Keterampilan menulis dan membuat konten yang kuat', 'Pengalaman dengan SEO/SEM dan pemasaran media sosial', 'Gairah untuk tujuan lingkungan'],
    postedAt: '10 hari yang lalu',
  },
  {
    id: 'rn-healthwell-1',
    title: 'Perawat Terdaftar',
    companyId: 'healthwell',
    companyName: 'HealthWell',
    companyLogo: 'employer-logo-4',
    location: 'Bali',
    category: 'Kesehatan',
    type: 'Paruh Waktu',
    description: 'Memberikan perawatan pasien berkualitas tinggi di fasilitas medis canggih kami.',
    longDescription: 'HealthWell sedang merekrut Perawat Terdaftar paruh waktu untuk bergabung dengan tim perawat kami yang penuh kasih dan terampil. Anda akan bertanggung jawab untuk menilai kebutuhan pasien, memberikan obat-obatan, dan memberikan perawatan dan pendidikan langsung kepada pasien dan keluarga mereka. Peran ini menawarkan jadwal yang fleksibel dan lingkungan kerja yang mendukung.',
    requirements: ['Lisensi RN yang valid', '2+ tahun pengalaman keperawatan', 'Sertifikasi BLS/CPR', 'Keterampilan komunikasi dan interpersonal yang sangat baik'],
    postedAt: '2 minggu yang lalu',
  }
];

export const featuredJobs = jobs.slice(0, 3);
export const topEmployers = employers.slice(0, 4);

export const jobCategories = [...new Set(jobs.map(job => job.category))];
export const jobLocations = [...new Set(jobs.map(job => job.location))];
